### ISSUE TITLE
transactionResponse cannot accept wildcard content 

### ISSUE THREAD

**Issue by ahopkins** [AuthorizeNet/sample-code-python#24]
I have a payment profile all setup, and now I am trying to capture from it.

I am trying to follow the code here: https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/charge-customer-profile.py 

However, everytime that I run the code verbatim as in the above script, I encounter this issue:

    StructuralBadDocumentError: {AnetApi/xml/v1/schema/AnetApiSchema.xsd}transactionResponse cannot accept wildcard content <pyxb.utils.saxdom.Element object at 0x7f8205dda850>

The full traceback:

    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/path/to/site-packages/authorizenet/apicontrollersbase.py", line 142, in execute
        self._response = apicontractsv1.CreateFromDocument(self._httpResponse)
      File "/path/to/site-packages/authorizenet/apicontractsv1.py", line 62, in CreateFromDocument
        saxer.parse(io.BytesIO(xmld))
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
        self._parser.Parse(data, isFinal)
      File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/path/to/site-packages/pyxb/binding/saxer.py", line 388, in endElementNS
        binding_object = this_state.endBindingElement()
      File "/path/to/site-packages/pyxb/binding/saxer.py", line 238, in endBindingElement
        _location=info.location)
      File "/path/to/site-packages/pyxb/binding/basis.py", line 2508, in append
        raise pyxb.StructuralBadDocumentError(container=self, content=value)
    StructuralBadDocumentError: {AnetApi/xml/v1/schema/AnetApiSchema.xsd}transactionResponse cannot accept wildcard content <pyxb.utils.saxdom.Element object at 0x7f8205dda850>

Anyone else seen this?

The weird thing is that the transaction is captured when I login to Authorize.net.

**Comment by adavidw** [comment]
Hi @ahopkins,

My apologies that nobody looked at this before. Did you ever get past this?

**Comment by ahopkins** [comment]
@adavidw thanks for the response. Not sure I remember if I did or not.
